# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup environment
    init: |
      echo "✔️ Environment setup complete. AWS CLI and PowerShell should be available."

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

  - name: terraform
    init: /workspaces/AWS-Study/s3/iac/terraform/install_terraform.sh

  #- name: aws-cdk
  #  init: |
   #   npm i -g aws-cdk
#npm install -g npm@11.4.2

#complete -C "$(which aws_completer)" aws
